DROP TABLE student;
CREATE TABLE student(
    StudentId NUMBER(6) PRIMARY KEY NOT NULL,
    l_name VARCHAR2(10) NOT NULL,
    f_name VARCHAR2(10) NOT NULL,
    street VARCHAR2(20) NOT NULL,
    city VARCHAR2(20),
    state VARCHAR2(20),
    zip NUMBER(7),
    StartTerm VARCHAR2(6),
    birthDate DATE,
    facultyId NUMBER(6),
    MajorId NUMBER(7),
    phone NUMBER(10)
);
DESC STUDENT;
CREATE TABLE FACULTY(
    FacultyId NUMBER(6), Name VARCHAR2(20), RoomId VARCHAR2(6), Phone NUMBER(10),DeptId NUMBER(6)
);
CREATE TABLE COURSE(
    CourseId VARCHAR2(6), Title VARCHAR2(6), Credits NUMBER(2), PreReq 
);
CREATE TABLE CRSSECTION(
    CsId VARCHAR2(6), CourseId VARCHAR2(6), Section VARCHAR2(4),
    TermId NUMBER(6), FacultyId NUMBER(6), Day DATE, StratTime TIME NOT NULL, EndTime TIME NOT NULL,
    RoomId VARCHAR2(6), MaxCount NUMBER(6) 
);
-- DROP TABLE CRSSECTION;
CREATE TABLE TERM(TermId NUMBER(6),TermDesc VARCHAR2(10), StartDate DATE, EndDate DATE);
CREATE TABLE ROOM (RoomType VARCHAR2(6), RoomDesc VARCHAR2(10));
CREATE TABLE REGISTRATION(StudentId NUMBER(6), CsId VARCHAR2(6), Midterm NUMBER(3), Final, RegStatus);
CREATE TABLE DEPARTMENT (DeptId NUMBER(6), DeptName VARCHAR2(6),FacultyId NUMBER(6));
CREATE TABLE MAJOR(MajorId NUMBER(7), MajorDesc VARCHAR2(10));
CREATE TABLE LOCATION (RoomId VARCHAR2(6), Building VARCHAR2(6), RoomNo NUMBER(4),
    Capacity NUMBER(2), RoomType VARCHAR2(6)
);
