CREATE TABLE EMP(
  EMPLOYEE_ID NUMBER(3),
  F_NAME VARCHAR(50),
  L_NAME VARCHAR(50),
  EMAIL VARCHAR(20),
  PHONE NUMBER(20),
  HIRE_DATE DATE,
  JOB_ID VARCHAR(20),
  SALARY NUMBER(10,2),
  COMMISSION_PCT NUMBER(4,2),
  MANAGER_ID NUMBER(3),
  DEPARTMENT_ID NUMBER(3)
);

CREATE TABLE DEPT ( DEPARTMENT_ID NUMBER(3),
DEPARTMENT_NAME VARCHAR2(26),
MANAGER_ID NUMBER(3),
LOCATION_ID NUMBER(5));

CREATE TABLE JOBS ( JOB_ID VARCHAR2(26),
JOB_TITLE VARCHAR2(50),
MIN_SALARY NUMBER(26),
MAX_SALARY NUMBER(26));

CREATE TABLE JOB_HISTORY ( EMPLOYEE_ID NUMBER(4),
START_DATE DATE,
END_DATE DATE,
JOB_ID VARCHAR2(20),
DEPARTMENT_ID NUMBER(4));

CREATE TABLE COUNTRY ( COUNTRY_ID VARCHAR2(3),
COUNTRY_NAME VARCHAR2(26),
REGION_ID NUMBER(2));

CREATE TABLE LOCATION ( LOCATION_ID NUMBER(5),
STREET_ADDRESS VARCHAR2(50),
POSTAL_CODE VARCHAR2(10),
CITY VARCHAR2(26),
STATE_PROVINCE VARCHAR2(26),
COUNTRY_ID VARCHAR2(3));